name: Maven Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Publish to CCBlueX Maven
      env:
        MAVEN_TOKEN_NAME: ${{ secrets.MAVEN_TOKEN_NAME }}
        MAVEN_TOKEN_SECRET: ${{ secrets.MAVEN_TOKEN_SECRET }}
      run: ./gradlew publish
